export const skillOptions = [
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "javascript", label: "JavaScript" },
  { value: "react", label: "React" },
  { value: "redux", label: "Redux" },
  { value: "material-ui", label: "Material UI" },
  { value: "tailwind-css", label: "Tailwind CSS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "nodejs", label: "Node.js" },
  { value: "expressjs", label: "Express.js" },
  { value: "mongodb", label: "MongoDB" },
  { value: "firebase", label: "Firebase" },
  { value: "graphql", label: "GraphQL" },
  { value: "docker", label: "Docker" },
  { value: "git", label: "Git" },
  { value: "postman", label: "Postman" },
  { value: "swagger", label: "Swagger" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "java", label: "Java" },
  { value: "spring-boot", label: "Spring Boot" },
  { value: "csharp", label: "C#" },
  { value: "dotnet", label: ".NET" },
  { value: "php", label: "PHP" },
  { value: "laravel", label: "Laravel" },
  { value: "angular", label: "Angular" },
];